export const SET_INPUT_VALUE = 'GAME/SET_INPUT_VALUE';
export const SET_IS_VALID_GUESS = 'GAME/SET_IS_VALID_GUESS';
export const SET_IS_GAME_OVER = 'GAME/SET_IS_GAME_OVER';

export const RESET_GUESS = 'GAME/RESET_GUESS';
